### ISSUE TITLE
 WebApplicationFactory with MSTest?

### ISSUE THREAD

**Issue by darrentraffk** [aspnet/AspNetCore.Docs#7749]
The above tutorial uses XUnit, but we're using MSTest in Visual Studio.  Is there a similar tutorial on how to use WebApplicationFactory with MSTest?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.1)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @darrentraffk ... There's no tutorial; but according to the engineer who wrote the framework code for testing, there's no significant difference between setting up the tests with MSTest versus xUnit. Both test frameworks should work with WebApplicationFactory. I didn't try MSTest when writing the topic, so I can't say myself if there are any "gotchas" along the way.

If you run into trouble setting up testing with MSTest, open an issue on the [aspnet/Home repo issues](https://github.com/aspnet/Home/issues) or Stack Overflow. If you find that the docs are missing critical information, please report back here.

**Comment by asadsahi** [comment]
@guardrex usage of NUnit is more than xUnit and MsTest I believe. So a tutorial of integration tests with NUnit will really help teams kick start with NUnit. Its good that we have a tutorial of NUnit Unit tests but I haven't managed to get NUnit working for integration test.

**Comment by guardrex** [comment]
I haven't tried to use NUnit and MSTest. I'm not opposed to building additional sample apps for the topic that use them.

@javiercn Can u comment? Any known issues? Do you think we should have sample apps based on the other test frameworks?

**Comment by javiercn** [comment]
I don't think there's any issue that I know of other than having to instantiate the web application factory yourself. (In xUnit you can use a fixture)

**Comment by guardrex** [comment]
I'm not opposed to providing samples for both ... the problem is time. We can open an issue to add them to the topic, but I can't say if the work would ever be done short of the community providing the samples.

**Comment by SWarnberg** [comment]
Yes, it would be great to get a direction on how to do this with MSTest. I'm struggling with it too.

**Comment by wadebee** [comment]
My concern is with disposal. I am looking at switching from my current usage of the TestServer class (which I understand is used within WebApplicationFactory. I currently use the following pattern:
`
using(var server = new TestServer(MyHostBuilder())) {
                using (var client = server.CreateClient())
                {
                    // add'l code here
                }
}
`
I see that WebApplicationFactory implements the Dispose method so am I to assume I should use the same pattern? In all the xUnit code samples you don't see any manual disposal code. Is this because of some "magic" happening in the xUnit implementation of IClassFixture<WebApplicationFactory<>>?

**Comment by guardrex** [comment]
@wadebee We recently added a bit to the topic on that point. See :point_right: https://docs.microsoft.com/aspnet/core/test/integration-tests#disposal-of-objects

**Comment by guardrex** [comment]
Yes, but Javier said ...

> instantiate the web application factory yourself

... so the principal is the same for MSTest, no? Can you handle your object disposal in your custom factory?

**Comment by wadebee** [comment]
This does not appear to work at all within MSTest. The test fails with:

> Exception thrown: 'System.InvalidOperationException' in Microsoft.AspNetCore.Mvc.Testing.dll

when CreateClient() is called. Also when I set a breakpoint on the offending line and view the factory variable from the Locals window something is very wrong: factory expands to 5 members however name, value and type for each member is completely blank. I haven't ever seen that in my debugger before.

Here is my code..
```
        [TestMethod]
        public async Task RootView()
        {
            using (var factory = new TestFactory())
            {
                using (var client = factory.CreateClient())
                {
                }
            }
         }
```

TestFactory is simple subclass like this:
`public class TestFactory : WebApplicationFactory<Startup> {}`

**Comment by guardrex** [comment]
ping @javiercn

**Comment by willj** [comment]
I too have been struggling to get this working with MSTest today, however I've now managed to make it work.

Here's a link to a repo with a single basic test in both MStest and xUnit 
https://github.com/willj/aspnet-core-mstest-integration-sample

I believe the issue I was having was related to the fact I was trying to do this on an older project, which has `BuildWebHost` instead of `CreateWebHostBuilder` in `Program.cs` (Which throws the InvalidOperationException @wadebee reports)

Additionally, make sure you add references to both `Microsoft.AspNetCore.App` and `Microsoft.AspNetCore.Mvc.Testing` in the MSTest project.

**Comment by guardrex** [comment]
Thanks for posting that @willj ... I'll get this scheduled for work in Q1-2019 if Javier would like me to pursue it. I think an exact copy of the current sample app that uses MSTest makes sense. We wouldn't need to expand the text much in that case. I can add a topic section that calls out the parallel sample, provide setup/config instructions, and list any caveats.

I appreciate it if you'll leave that GH sample online for me to :eyes: when the time comes. If you think you will pull it down, let me know here, and I'll look sooner.

**Comment by willj** [comment]
No problem, I don't delete anything so that will remain online 👍 

In reality, I think as long as you File -> New Project this just works as expected, however I think it would be useful to have the sample and some notes as I couldn't find anything about this in my searches yesterday.

If I get chance over the next couple of weeks, would it be helpful for me to have a go at this?

**Comment by scottaddie** [comment]
@guardrex I'm working with the team to get approval for "xUnit", "MSTest", and "NUnit" tabs. This could be a slow-moving request due to the holidays. Proceed with the assumption that we have approval.

**Comment by scottaddie** [comment]
@guardrex These tabs are approved. The syntax will be:

•	`[MSTest](#tab/mstest)`
•	`[NUnit](#tab/nunit)`
•	`[xUnit](#tab/xunit)`

**Comment by voroninp** [comment]
@willj interesting enough `Microsoft.NET.Sdk.Web` is not referenced in test project, though everything works. However this doc clearly states:

>The Web SDK is required when referencing the Microsoft.AspNetCore.App metapackage.

**Comment by javiercn** [comment]
This was due to some issue we had during the 2.1 release that I believe got fixed in 2.2, but I don't remember the exact details

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.

**Comment by changhuixu** [comment]
Hi to all above and future MSTest users,

I have an example integration test using MSTest, link below
https://github.com/dotnet-labs/AngularFileUpload/blob/master/MyApp.IntegrationTests/WeatherForecastControllerTests.cs

Hope it helps.

**Comment by ayodejii** [comment]
This is still a problem in .NET projects without the `Startup` class, especially when you need to remove and "re-register" a service or use a different database from the one your app use and you use a custom `WebApplicationFactory` class and override the `void ConfigureWebHost(IWebHostBuilder builder)` method.

The method is not called. I created a [SO question](https://stackoverflow.com/questions/76500548/why-is-the-configurewebhostiwebhostbuilder-builder-of-the-webapplicationfactor/76509606#76509606) for this.

Please help look into it. Thank you.
